import {useEffect,useState} from 'react';
import * as api from '../lib/api';

export function Intelligence({model, onUpdate}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[points,setPoints]=useState([]);
  useEffect(()=>{let live=true;if(model?.trained)api.getModelForecast().then(r=>{if(live)setPoints(r.forecast)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[model?.trained_at,model?.trained]);
  const train=async(dataset)=>{setBusy(true);setError('');try{await api.trainModel(dataset);await onUpdate()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="intelligence-page"><section className="panel learning-intro"><span className="eyebrow">SUPERVISED FORECASTING</span><h2>A model you can inspect.</h2><p>Seasonal ridge regression learns the daily carbon pattern from historical observations. The last 48 available observations are held out for evaluation, then the final model is refitted on the complete history.</p><div className="learning-actions"><button className="btn primary" disabled={busy} onClick={()=>train('public_history')}>{busy?'Training…':'Train on public UK history'}</button><button className="btn" disabled={busy} onClick={()=>train('synthetic_demo')}>Train with offline fixture</button></div><p className="fine-print">Offline training uses synthetic data and tests the software only. It does not establish real-world forecast accuracy. Learned forecasts are available for GB national jobs; regional forecasts continue to use their own data.</p>{error&&<p className="error-text" role="alert">{error}</p>}</section>{model?.trained?<><div className="model-metrics"><div className="metric"><div className="metric-label">Held-out mean absolute error</div><div className="metric-value">{model.mae_gco2_kwh}<small>gCO₂/kWh</small></div><span>{model.test_samples} held-out observations</span></div><div className="metric"><div className="metric-label">Previous-day baseline error</div><div className="metric-value">{model.baseline_mae_gco2_kwh}<small>gCO₂/kWh</small></div><span>{model.beats_baseline?'Model improved on this baseline':'Model did not beat this baseline'}</span></div><div className="metric"><div className="metric-label">Training observations</div><div className="metric-value">{model.train_samples}</div><span>{model.dataset}</span></div></div><section className="panel model-evidence"><h2>Validation & provenance</h2><dl><dt>Training ended</dt><dd>{model.training_end}</dd><dt>Holdout began</dt><dd>{model.validation_start}</dd><dt>Algorithm</dt><dd>{model.algorithm}</dd><dt>Data source</dt><dd>{model.dataset}</dd><dt>Historical 90th-percentile absolute error</dt><dd>{model.residual_p90_gco2_kwh} gCO₂/kWh</dd></dl><p className="fine-print">{model.uncertainty_note}. Forecasts have no guaranteed accuracy. A failed baseline comparison remains visible.</p><div className="prediction-strip">{points.slice(0,8).map(p=><div key={p.timestamp}><small>{new Date(p.timestamp).toISOString().slice(11,16)} UTC</small><strong>{p.intensity_gco2_kwh.toFixed(1)}</strong><small>predicted gCO₂/kWh</small></div>)}</div></section></>:<div className="empty"><h3>No trained model yet.</h3><p>Choose a dataset to fit the model and view its validation results.</p></div>}</div>
}

export function Regions({regions, mode, Forecast, nowIso, onUpdate}) {
  const [selected,setSelected]=useState('gb'),[rows,setRows]=useState([]),[error,setError]=useState(''),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[horizon,setHorizon]=useState(24);
  useEffect(()=>{let live=true;api.getRegionForecast(selected).then(r=>{if(live){setRows(r.forecast);setError('')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[selected,mode,nowIso]);
  const template=()=>{const start=Math.floor(Date.parse(nowIso)/1800000)*1800000;setDraft(JSON.stringify({region:'in-north',source_name:'Replace with your forecast source',rows:Array.from({length:49},(_,i)=>({timestamp:new Date(start+i*1800000).toISOString(),intensity_gco2_kwh:650}))},null,2))};
  const upload=async()=>{setBusy(true);setError('');try{const body=JSON.parse(draft);await api.importForecast(body);setSelected(body.region);await onUpdate()}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="regions-page"><p className="region-disclosure">{mode==='scenario'?'Synthetic regional scenario is active. All regional values are demonstration assumptions.':'Available UK regional forecasts come from NESO. Indian forecasts require a connected provider or an operator-supplied import.'} Every workload executes on this computer. SHIFT is a recommendation demonstrated locally.</p><div className="region-cards">{regions.map(r=><button key={r.id} className={'region-card '+(selected===r.id?'selected':'')} onClick={()=>setSelected(r.id)}><span>{r.country==='IN'?'INDIA':'UNITED KINGDOM'}</span><h3>{r.name}</h3><strong>{r.current?Math.round(r.current.intensity_gco2_kwh):'—'}<small>gCO₂/kWh</small></strong><p>{r.available?r.current.source_kind.replaceAll('_',' '):'Not connected'}</p><small>{r.source}</small></button>)}</div>{rows.length>1?<Forecast slots={rows} decision={null} horizon={horizon} setHorizon={setHorizon}/>:<div className="empty"><h3>There is no usable forecast for this region.</h3><p>Import a supplied forecast below or start the labelled guided scenario on Simulation.</p></div>}<details className="panel forecast-import"><summary>Import an Indian forecast</summary><p>Supply consecutive UTC half-hour rows in gCO₂/kWh. Imports are labelled as operator-supplied, never independently verified telemetry.</p><button className="btn" onClick={template}>Load editable JSON example</button><textarea aria-label="Indian forecast JSON" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Paste forecast JSON here"/><button className="btn primary" disabled={busy||!draft} onClick={upload}>{busy?'Importing…':'Import forecast'}</button></details>{error&&<p role="alert" className="error-banner">{error}</p>}</div>
}
